# Description
title: rockadudle
email: rockadudle@gmail.com
description: rockadudle
baseurl: ""
url: ""
twitter_username: ""
github_username:  Robinseibold

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination settings
paginate: 5
paginate_path: "/feed/page:num/"

# sass settings
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
- games
